%drgMini_display_DecodeDynamicOdorConc.m
close all
clear all



%Initial file use to troubleshoot the code
% handles_choices.save_path='/Users/restrepd/Documents/Projects/SFTP/Fabio_OdorArena_GoodData/PreProcessed/test/';
% arena_file='20221117_FCM22withodor_nearfloor_odorarena_L1andL4_fix_sync_mm.mat';
% load([handles_choices.save_path arena_file(1:end-4) handles_choices.save_tag '.mat'])

%The file that is used here is generated by drgMini_batch_DecodeDynamicOdorConc.m

%Trained with all trials and mult=0.5 taking on account when mouse detects the odor
% save_PathConc='/Users/restrepd/Documents/Projects/SFTP/Fabio_OdorArena_GoodData/DecodeDynOdorConc11112025/';
% choiceOdorConcFileName='drgDynamicOdorConcChoices_Fabio_bin_all_11112025.m';
% dyn_conc_file='20221117_FCM22withodor_nearfloor_odorarena_L1andL4_fix_sync_mmdynconctree0p5.mat';


%Trained with all trials and mult=1 taking on account when mouse detects the odor
save_PathConc='/Users/restrepd/Documents/Projects/SFTP/Fabio_OdorArena_GoodData/DecodeDynOdorConc_1_11222025/';
% choiceOdorConcFileName='drgDynamicOdorConcChoices_Fabio_bin_all_1_11222025.m';
dyn_conc_file='20221117_FCM22withodor_nearfloor_odorarena_L1andL4_fix_sync_mmdynconctree1.mat';

load([save_PathConc dyn_conc_file])

%Please note that because of a problem with coding
%handles_choices.bins_before=0 for files created before 3/1/26
% Specify your .mat file path
filename = [save_PathConc dyn_conc_file];  % Change this to your file path

% Get file info
d = dir(filename);

% Convert file modification date to datetime
fileDate = datetime(d.date);  

% Reference date: March 1, 2026
refDate = datetime(2026, 3, 1, 0, 0, 0);


% Check if file date is before March 1, 2026
if fileDate < refDate
    handles_choices.bins_before=0;
    bb=0;
    fprintf('File date %s is before March 1, 2026. bb = %d\n', string(fileDate), bb);
end


odor_plume_template=handles_out.odor_plume_template;
op_predicted=handles_out.op_predicted;

trials=handles_out.trials;

no_conv_points=11;
% conv_win=ones(1,no_conv_points)/no_conv_points;
conv_win_gauss = gausswin(no_conv_points);
conv_win_gauss=conv_win_gauss/sum(conv_win_gauss);

op_predicted_conv=conv(op_predicted,conv_win_gauss,'same');

%Now limit the x and y to max and min
minop=min(odor_plume_template);
op_predicted_conv(op_predicted_conv<minop)=minop;
maxop=max(odor_plume_template);
op_predicted_conv(op_predicted_conv>maxop)=maxop;

dt=handles_choices.dt;

figNo=0;
figNo=figNo+1;
try
    close(figNo)
catch
end

hFig = figure(figNo);

set(hFig, 'units','normalized','position',[.1 .1 .7 .25])


hold on
ii_start=0;

op_predictedstart=1;
op_predictedend=length(op_predicted(:,1));
% plot(odor_plume_template(op_predictedstart:op_predictedend),'Color',[0.6 0.6 1],'LineWidth',3)
% plot(op_predicted_conv(op_predictedstart:op_predictedend),'-k','LineWidth',1.5)

maxop=max(odor_plume_template(op_predictedstart:op_predictedend));
minop=min(odor_plume_template(op_predictedstart:op_predictedend));

wall_threshold=50;
op_all_trials=[];

for trNo=1:trials.odor_trNo

    op_predictedstart=trials.odor_ii_start(trNo)+handles_choices.trial_start_offset;
    op_predictedend=trials.odor_ii_end(trNo)+handles_choices.trial_end_offset;
    if op_predictedend>length(odor_plume_template)
        op_predictedend=length(odor_plume_template);
    end

    op_all_trials=[op_all_trials; odor_plume_template(op_predictedstart:op_predictedend)'];
    % op_decod_all_trials=[op_decod_all_trials; op_predicted_conv(op_predictedstart:op_predictedend)];
    % 
    % op_between_trials=[op_between_trials; odor_plume_template(last_op_predictedend:op_predictedstart)'];
    % op_decod_between_trials=[op_decod_between_trials; op_predicted_conv(last_op_predictedend:op_predictedstart)];
    % last_op_predictedend=op_predictedend;

    ii_end=ii_start+length(odor_plume_template(op_predictedstart:op_predictedend))-1;

   


    %Okabe_Ito colors
    switch trials.odor_trial_type(trNo)
        case 1
            %Lane 1 hits vermillion
            plot(dt*[ii_start:ii_end]',odor_plume_template(op_predictedstart:op_predictedend)','Color',[230/255 159/255 0/255],'LineWidth',2)
            plot(dt*[ii_start:ii_end]',op_predicted_conv(op_predictedstart:op_predictedend)','-k','LineWidth',1)
            plot(dt*[ii_start+10 ii_start+10],[minop maxop],'-k')
            plot(dt*[ii_end-15 ii_end-15],[minop maxop],'-k')
            % op_all_hits=[op_all_hits; odor_plume_template(op_predictedstart:op_predictedend)'];
            % op_decod_all_hits=[op_decod_all_hits; op_predicted_conv(op_predictedstart:op_predictedend)];
        case 2
            %Lane 1 miss orange
            plot(dt*[ii_start:ii_end]',odor_plume_template(op_predictedstart:op_predictedend),'Color',[86/255 180/255 233/255],'LineWidth',2)
            plot(dt*[ii_start:ii_end]',op_predicted_conv(op_predictedstart:op_predictedend)','-k','LineWidth',1)
            plot(dt*[ii_start+10 ii_start+10],[minop maxop],'-k')
            plot(dt*[ii_end-15 ii_end-15],[minop maxop],'-k')
            % op_all_miss=[op_all_miss; odor_plume_template(op_predictedstart:op_predictedend)'];
            % op_decod_all_miss=[op_decod_all_miss; op_predicted_conv(op_predictedstart:op_predictedend)];

        case 3
            %Lane 4 hit blue
            plot(dt*[ii_start:ii_end]',odor_plume_template(op_predictedstart:op_predictedend)','Color',[230/255 159/255 0/255],'LineWidth',2)
            plot(dt*[ii_start:ii_end]',op_predicted_conv(op_predictedstart:op_predictedend)','-k','LineWidth',1)
            plot(dt*[ii_start+10 ii_start+10],[minop maxop],'-k')
            plot(dt*[ii_end-15 ii_end-15],[minop maxop],'-k')
            % op_all_hits=[op_all_hits; odor_plume_template(op_predictedstart:op_predictedend)'];
            % op_decod_all_hits=[op_decod_all_hits; op_predicted_conv(op_predictedstart:op_predictedend)];
        case 4
            %Lane 4 miss sky blue
            plot(dt*[ii_start:ii_end]',odor_plume_template(op_predictedstart:op_predictedend)','Color',[86/255 180/255 233/255],'LineWidth',2)
            plot(dt*[ii_start:ii_end]',op_predicted_conv(op_predictedstart:op_predictedend)','-k','LineWidth',1)
            plot(dt*[ii_start+10 ii_start+10],[minop maxop],'-k')
            plot(dt*[ii_end-15 ii_end-15],[minop maxop],'-k')
            % op_all_miss=[op_all_miss; odor_plume_template(op_predictedstart:op_predictedend)'];
            % op_decod_all_miss=[op_decod_all_miss; op_predicted_conv(op_predictedstart:op_predictedend)];
    end

    ii_start=ii_start+length(odor_plume_template(op_predictedstart:op_predictedend))+20;
end

ylim([min(op_all_trials)-0.1*(max(op_all_trials)-min(op_all_trials)) max(op_all_trials)+0.1*(max(op_all_trials)-min(op_all_trials))])

title(['mult*log(OC), vermillion: HIT, sky blue: MISS ' dyn_conc_file(1:end-4)],'Interpreter', 'none')

aligned_miss_template=handles_out.aligned_miss_template;
aligned_hit_template=handles_out.aligned_hit_template;
aligned_miss_predicted=handles_out.aligned_miss_predicted;
aligned_hit_predicted=handles_out.aligned_hit_predicted;
ii_t_before=handles_out.ii_t_before;
ii_t_after=handles_out.ii_t_after;

figNo=figNo+1;
try
    close(figNo)
catch
end

hFig = figure(figNo);

set(hFig, 'units','normalized','position',[.1 .1 .3 .3])


hold on

%Plot hit
this_time=[1:-ii_t_before+ii_t_after+1]*dt;


CIsp = bootci(1000, @mean, aligned_hit_template);
meansp=mean(aligned_hit_template,1);
CIsp(1,:)=meansp-CIsp(1,:);
CIsp(2,:)=CIsp(2,:)-meansp;

[hlpvl, hppvl] = boundedline(this_time,mean(aligned_hit_template,1)', CIsp','cmap',[230/255 159/255 0/255]);
plot(this_time,mean(aligned_hit_template,1)','Color',[230/255 159/255 0/255],'LineWidth',3);

% CIsp = bootci(1000, @mean, aligned_hit_predicted);
% meansp=mean(aligned_hit_predicted,1);
% CIsp(1,:)=meansp-CIsp(1,:);
% CIsp(2,:)=CIsp(2,:)-meansp;
%
% [hlpvl, hppvl] = boundedline(this_time,mean(aligned_hit_predicted,1)', CIsp','cmap',[0 0 0]);

plot(this_time,mean(aligned_hit_predicted,1)','Color',[0.6*230/255 0.6*159/255 0.6*0/255],'LineWidth',2)


%Plot miss
this_time=this_time+1.2*(-ii_t_before+ii_t_after+1)*dt;


CIsp = bootci(1000, @mean, aligned_miss_template);
meansp=mean(aligned_miss_template,1);
CIsp(1,:)=meansp-CIsp(1,:);
CIsp(2,:)=CIsp(2,:)-meansp;

[hlpvl, hppvl] = boundedline(this_time,mean(aligned_miss_template,1)', CIsp','cmap',[86/255 180/255 233/255]);
plot(this_time,mean(aligned_miss_template,1)','Color',[86/255 180/255 233/255],'LineWidth',3);

% % CIsp = bootci(1000, @mean, aligned_miss_predicted);
% % meansp=mean(aligned_miss_predicted,1);
% % CIsp(1,:)=meansp-CIsp(1,:);
% % CIsp(2,:)=CIsp(2,:)-meansp;
% %
% % [hlpvl, hppvl] = boundedline(this_time,mean(aligned_miss_predicted,1)', CIsp','cmap',[0 0 0]);
%
plot(this_time,mean(aligned_miss_predicted,1)','Color',[0.6*86/255 0.6*180/255 0.6*233/255],'LineWidth',2)

title(['Mean log10(odor) vs. predicted mult= ' num2str(handles_choices.multiplier) ' bb= ' num2str(handles_choices.bins_before)])
this_ylim=ylim;
plot([this_time(-ii_t_before) this_time(-ii_t_before)],this_ylim,'-k','LineWidth',1)
xlabel('Time (sec)')
ylabel('log10(odor) AU')

%Plot each trial
max_all=max([max(aligned_hit_template(:)) max(aligned_miss_template(:))]);
min_all=min([min(aligned_hit_template(:)) min(aligned_miss_template(:))]);

figNo=figNo+1;
try
    close(figNo)
catch
end

hFig = figure(figNo);

set(hFig, 'units','normalized','position',[.1 .1 .3 .7])


hold on

%Plot hit
this_time=[1:-ii_t_before+ii_t_after+1]*dt;

y_shift1=0;

for trNo=1:size(aligned_hit_template,1)
    plot(this_time,aligned_hit_template(trNo,:)+y_shift1,'Color',[230/255 159/255 0/255],'LineWidth',2)
    plot(this_time,aligned_hit_predicted(trNo,:)+y_shift1,'-k','LineWidth',1)
    y_shift1=y_shift1+1.5*(max_all-min_all);
end

% plot([this_time(-ii_t_before) this_time(-ii_t_before)],[0 y_shift1],'-k')

title(['HIT mult= ' num2str(handles_choices.multiplier) ' bb= ' num2str(handles_choices.bins_before)])

figNo=figNo+1;
try
    close(figNo)
catch
end

hFig = figure(figNo);

set(hFig, 'units','normalized','position',[.1 .1 .3 .7])


hold on

%Plot hit
this_time=[1:-ii_t_before+ii_t_after+1]*dt;

y_shift2=0;

for trNo=1:size(aligned_miss_template,1)
    plot(this_time,aligned_miss_template(trNo,:)+y_shift2,'Color',[86/255 180/255 233/255],'LineWidth',2)
    plot(this_time,aligned_miss_predicted(trNo,:)+y_shift2,'-k','LineWidth',1)
    y_shift2=y_shift2+1.5*(max_all-min_all);
end

y_shift_max=max([y_shift1 y_shift2]);
plot([this_time(-ii_t_before) this_time(-ii_t_before)],[0 y_shift_max],'-k')

title(['MISS mult= ' num2str(handles_choices.multiplier) ' bb= ' num2str(handles_choices.bins_before)])


ylim([0 y_shift_max])
xlim([3.5 7.5])

figure(figNo-1)
ylim([0 y_shift_max])
xlim([3.5 7.5])
plot([this_time(-ii_t_before) this_time(-ii_t_before)],[0 y_shift_max],'-k')

R1=handles_out.R1.all_trials;
fprintf(1, 'Correlation coefficient nn conv odor conc within trials %d\n\n',R1);

R1=handles_out.R1.all_hits;
fprintf(1, 'Correlation coefficient nn conv odor conc hits %d\n\n',R1);

R1=handles_out.R1.all_miss;
fprintf(1, 'Correlation coefficient nn conv odor conc miss %d\n\n',R1);

pffft=1;